# Site
name: "Harzer Wanderbuddy"
title: "Harzer Wanderbuddy"
description: "Dein Buddy zum Planen von Touren rund um die Harzer Wandernadel!"
logo: 'assets/images/BuddyWithMapNoBG.png'
favicon: 'assets/images/BuddyWithMapNoBG.png'
baseurl: ''
#google_analytics: 'UA-xxxxxxxx-1' #also comment back in, in default.html
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: info@harzer-wander-buddy.com
formspreePath: f/mzzddkdr

# Authors
authors:
  buddy:
    name: Buddy
    display_name: Buddy
    avatar: 'assets/images/avatar-Buddy.png'
    instagram: https://www.instagram.com/harzer_wanderbuddy
    description: 'Dein Harzer Wanderbuddy! Buddy ist dein Hefler beim Planen von Touren. Ich arbeite fleißig an einer <strong><a href="/app-waitlist">App <span class="badge badge-primary">NEU</span></a></strong> um dir das Planen von Touren zu erleichtern. Tritt noch heute unserer Warteliste bei und erfahre als Erster von Neuerungen!'
  jace:
    name: Jace
    display_name: Jace
    avatar: 'assets/images/avatar-Jace.png'
    description: "Jace ist unser Tester hinsichlich der Hundefreundlichkeit. Auch wenn er noch nicht alle Stempelstellen besucht hat, berichtet er von persönlichen Erfahrungen auf seinen Wanderungen!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, verifyLinkIntegrity]
